Add rmwait and rmadd scripts

diff --git a/sh/rmssh b/sh/rmssh
--- a/sh/rmssh
+++ b/sh/rmssh
@@ -15,6 +15,8 @@ esac
 
 while test -n "$1" ; do
   case "$1" in
+    --gui) RM_GUI=y;;
+    --no-gui) RM_GUI=n;;
     -D) RM_DEVICE="$2" ; shift ;;
     -v|--verbose) RM_VERBOSE=y ;;
     --no-timeout) NCTO='' ;;
@@ -23,6 +25,7 @@ while test -n "$1" ; do
       echo "$SNAME [-D (A|B)] [--no-timeout] [-v|--verbose] [--log FILE] SSH_ARGS..." >&2;
       exit 1
       ;;
+    --) shift; break ;;
     *) CMD="$CMD $1" ;;
   esac
   shift
@@ -33,26 +36,30 @@ if test "$RM_VERBOSE" = "y" ; then
 fi
 
 T=$(mktemp -d --tmpdir)
-trap "rm -rf '$T'" 0 1 2 3 9
+trap "rm -rf '$T'" 0 1 3 9
 if test -z "$LOG"; then
   LOG=$T/rmpull_$UID.txt
 fi
 
-{
+(
+  trap "exit 1" 2
   if test -n "$RM_VPSSSH" ; then
     VPSRPORT=`rmvpsrport`
     $SSHTOOL \
       -o "ProxyCommand ssh $RM_VPSSSH nc $NCTO 127.0.0.1 $VPSRPORT" \
       -o "StrictHostKeyChecking=no" \
-      $CMD
+      $CMD "$@"
   else
     $SSHTOOL \
       -o "StrictHostKeyChecking=no" \
-      $CMD
+      $CMD "$@"
   fi
   echo "$?" >$T/RET
-} 2>&1 | tee -a "$LOG"
+) 2>&1 | tee -a "$LOG"
 
+RET=$(cat "$T/RET")
 if test x$(cat "$T/RET") != "x0" ; then
-  rmdieL "$LOG" "Failed to restart remarkable gui, code $RET"
+  ( rmdieL "$LOG" "Failed to restart remarkable gui, code $RET" ; )
 fi
+
+exit $RET
